FROM archlinux:base

RUN pacman -Sy --noconfirm librsvg mupdf-tools python python-pip

COPY requirements.txt .
RUN pip install -U pip && \
    pip install -r requirements.txt

WORKDIR /app

COPY . /app

ENTRYPOINT ["python", "generate_qr_cards.py"]
